#!/usr/bin/env node
/* ============================================================
   Lesson manifest generator — CLI

   Regenerates lessons/foundation-release-1/manifest.json from the
   actual lesson source files. The manifest is a GENERATED artifact,
   never hand-edited, and never the source of truth for anything —
   see docs/lesson-authoring/README.md "Static index".

   Refuses to write a manifest if any lesson file fails validation,
   so the manifest can never describe invalid data.

     node tools/lesson-index.mjs
   ============================================================ */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadCorpus } from '../src/curriculum/loader.js';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const releaseDir = path.join(root, 'lessons', 'foundation-release-1');
const manifestPath = path.join(releaseDir, 'manifest.json');

function walk(dir) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith('_')) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else if (entry.isFile() && entry.name.endsWith('.json') && entry.name !== 'manifest.json') out.push(full);
  }
  return out;
}

const files = walk(releaseDir).sort();
const entries = files.map((file) => ({
  file: path.relative(root, file).replace(/\\/g, '/'),
  raw: JSON.parse(fs.readFileSync(file, 'utf8')),
}));

const { lessons, errors } = loadCorpus(entries);
const hardErrors = errors.filter((e) => e.severity !== 'warning');
if (hardErrors.length) {
  console.error(`Refusing to generate manifest.json — ${hardErrors.length} validation problem(s). Run "npm run lessons:validate" for details.`);
  process.exit(1);
}

const manifest = {
  _generated: 'This file is generated by `node tools/lesson-index.mjs`. Do not hand-edit — it will be overwritten. Source of truth is the individual lesson JSON files.',
  generatedAt: new Date().toISOString().slice(0, 10),
  schemaVersion: 1,
  count: lessons.length,
  lessons: lessons
    .map(({ file, lesson }) => ({
      id: lesson.id,
      unitId: lesson.unitId,
      sequence: lesson.sequence,
      title: lesson.title,
      domain: lesson.domain,
      type: lesson.type,
      sourceFile: file,
      schemaVersion: lesson.schemaVersion,
      representations: lesson.representations.map((r) => r.type),
    }))
    .sort((a, b) => (a.unitId === b.unitId
      ? (a.sequence ?? Infinity) - (b.sequence ?? Infinity)
      : a.unitId.localeCompare(b.unitId, undefined, { numeric: true }))),
};

fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n');
console.log(`Wrote ${manifestPath.replace(root + path.sep, '')} — ${lessons.length} lesson(s) indexed.`);
